### ISSUE TITLE
Add a nested_virt option

### ISSUE THREAD

**Issue by rthallisey** [ansibleplaybookbundle/kubevirt-apb#17]
Add a nested_virt param to the kubevirt-apb.  This is going to require running:
```
echo "options kvm-intel nested=1" > /etc/modprobe.d/kvm-intel.conf
rmmod kvm-intel && modprobe kvm-intel || true
cat /sys/module/kvm_intel/parameters/nested
```

In order for this to work, the container needs to be a root user and needs to mount in ```/lib/modules```.

**Comment by mareklibra** [comment]
To support both Intel and AMD:
```
if [ -d /sys/module/kvm_intel -a -d /etc/modprobe.d -a ! -f /etc/modprobe.d/kvm-intel.conf ]; then
    echo "options kvm-intel nested=1" > /etc/modprobe.d/kvm-intel.conf
    rmmod kvm-intel && modprobe kvm-intel || true
fi
if [ -d /sys/module/kvm_amd -a -d /etc/modprobe.d -a ! -f /etc/modprobe.d/kvm-amd.conf ]; then
    echo "options kvm-amd nested=1" > /etc/modprobe.d/kvm-amd.conf
    rmmod kvm-amd && modprobe kvm-amd || true
fi
```

To verify:
```
cat /sys/module/kvm_intel/parameters/nested
```

**Comment by karmab** [comment]
i'll be a bit picky and suggest *modprobe -r* instead of *rmmod*

**Comment by mareklibra** [comment]
works for me ...

**Comment by karmab** [comment]
i dont get in which container this code should go

**Comment by rthallisey** [comment]
@karmab can you explain further?

**Comment by karmab** [comment]
@rthallisey sure, you re saying in first comment the following
```
In order for this to work, the container needs to be a root user and needs to mount in /lib/modules.
```

and it dont get which container you re talking about:
- the kubevirt ones
- the apb one

**Comment by rthallisey** [comment]
The kubevirt-apb need to be root and mount /lib/modules.

Switching to Root: https://github.com/ansibleplaybookbundle/kubevirt-apb/pull/19/files#diff-3254677a7917c6c01f55212f86c57fbfL23

**Comment by karmab** [comment]
actually what i meant is that the apb would be creating a vm object (crd) living in a different namespace than the one it s currently deployed, for me this didnt work, but maybe i m wrong ( and it has to do with the next section ).

but it's worse, because even if the apb can create objects in the destination namespace, we would get errors like the following, though the user does belong to the indicated namespace

```
[jmayer@master01 ~]$ oc get vm
Error from server (Forbidden): virtualmachines.kubevirt.io is forbidden: User "jmayer" cannot list virtualmachines.kubevirt.io in the namespace "woodstock": User "jmayer" cannot list virtualmachines.kubevirt.io in project "woodstock"
```

**Comment by nellyc** [comment]
@rthallisey where is this req coming forom? is it still relevant?

**Comment by rthallisey** [comment]
closing for now.
