### ISSUE TITLE
This APB should consume kubevirt.yaml release

### ISSUE THREAD

**Issue by lukas-bednar** [ansibleplaybookbundle/kubevirt-apb#2]
This repository contains static templates which are the kubevirt.yaml itself just broken down into separated files one per each kind. I am talking about templates located under following directory.
https://github.com/ansibleplaybookbundle/kubevirt-apb/tree/master/roles/kubevirt-apb/templates

In my opinion this APB is supposed to consume kubevirt.yaml which is part of KubeVirt release.
https://github.com/kubevirt/kubevirt/releases

**Comment by rthallisey** [comment]
Correct me if I'm wrong @karmab, but @karmab used his project https://github.com/karmab/ttapb to generate the playbooks from https://github.com/kubevirt/kubevirt/blob/master/manifests/release/kubevirt.yaml.in.  With this tool, we could regenerate the playbooks on a per commit basis to ```kubevirt.yaml.in```.

**Comment by lukas-bednar** [comment]
@rthallisey if it is like this, then I don't have problem with it.
And think there should be process to regenerate it on every kubevirt release.

Just note: I think it should be generated from released manifest, no? For example: https://github.com/kubevirt/kubevirt/releases/download/v0.2.0/kubevirt.yaml instead of `kubevirt.yaml.in`.

**Comment by rthallisey** [comment]
@lukas-bednar I think that makes sense when we tag a release for the apb so we're right in sync with kubevirt release.  But during the development cycle, I think we want to pull from the latest templates so developers will always have the latest bits.

**Comment by karmab** [comment]
indeed the idea is  to use the tooling to generate the playbook from the release file
i also believe that at some point, the tool ( which intends to be generic, not kubevirt specific) wont be needed as only the targetted version will change and not the manifests per se
